AWSTemplateFormatVersion: '2010-09-09'

Description: Blog template


Parameters:
  BlogName:
    Description: Name of the blog 
    Type: String
  DomainName:
    Description: Top level domain name
    Type: String
  CertARN:
    Description: Certificate ARN
    Type: String

    
Resources:
  RootBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub '${BlogName}.${DomainName}'
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  RootBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref RootBucket
      PolicyDocument:
        Statement:
          - Action:
            - 's3:GetObject'
            Effect: Allow
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref RootBucket
                - /*
            Principal: 
              CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId
            Sid: PublicReadGetObject

  CloudFrontOriginAccessIdentity:
    Type: 'AWS::CloudFront::CloudFrontOriginAccessIdentity'
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Ref RootBucket

  WWWBucket:
    Type: AWS::S3::Bucket
    DependsOn: RootBucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub 'www.${BlogName}.${DomainName}'
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !Ref RootBucket

# Remove certificate creation from this cloudformation
#
#  CertificateManagerCertificate:
#    Type: AWS::CertificateManager::Certificate
#    Properties:
#      DomainName: !Sub '${BlogName}.${DomainName}'
#      ValidationMethod: DNS
#

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn: RootBucket
    Properties:
      DistributionConfig:
        Enabled: true
        HttpVersion: http2
        PriceClass: PriceClass_All
        ViewerCertificate:
          AcmCertificateArn: !Ref 'CertARN'
          MinimumProtocolVersion: TLSv1.1_2016
          SslSupportMethod: sni-only
        Aliases:
          - !Sub '${BlogName}.${DomainName}'
        Origins:
          - DomainName: !GetAtt 'RootBucket.DomainName'
            Id: !Sub 'S3-${AWS::StackName}-root'
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}'
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          TargetOriginId: !Sub 'S3-${AWS::StackName}-root' 
          ViewerProtocolPolicy: 'redirect-to-https'
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: true

  Route53:
    Type: AWS::Route53::RecordSet
    DependsOn: CloudFrontDistribution
    Properties:
      HostedZoneName: !Sub '${DomainName}.'
      Comment: !Sub 'Entry point for ${BlogName}.${DomainName}'
      Name: !Sub '${BlogName}.${DomainName}'
      Type: CNAME
      TTL: '900'
      ResourceRecords:
        - !GetAtt CloudFrontDistribution.DomainName
